#!/bin/sh

# NOTES
#	- After this, you'll be able use ssh instead of https when
#	  interacting with Github.
#
$user_name=$1
$user_email=$2

git config --global user.email $user_email
git config --global user.name $user_name

ssh-keygen -t ed25519 -C $user_email

cat ~/.ssh/*pub




