#!/bin/sh

# A script that lists all binaries on your
# computer.
# /bin          , /sbin,
# /usr/bin      , /usr/sbin,
# /usr/local/bin, /usr/local/sbin


find /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin -type f -perm +111
