#!/bin/sh

# DESCRIPTION
# 	Given a file, this script shows which package installed it.
#	
#	As fun exercise, go to /usr/local/bin and run this command on
#	one of the files. Then run `pkg info <package>` on the result
#	to know more about what that package does. But watch out! you
#	might learn something you didn't know you didn't know. :)
# USAGE
# 	./pkg-what-installed-this <file-name>
# NOTES
#

pkg which $1
