#!/bin/sh

# USAGE
# 	./this-script <package-name>
#
# DESCRIPTION
# 	Shows you the raw manifest file for a given package. 
# 	This file constains any information you might want to 
# 	know about a package.
# NOTES
#

pkg info -R $1
