#!/bin/sh
# USAGE
# 	./this-script
#
# DESCRIPTION
#  "Dump[s] a list of all non-default configuration variables" ... that
#  are allowed to be placed in the /etc/rc.conf file which contains all
#  of the services you can enable.
#
# NOTES
# - To describe just once kernel state, run `sysctl -d <service>`
# SEE
# - sysrc man page  : SYSRC(8)
# - rc.conf man page: RC.CONF(5)


sysrc -Ad
