#!/bin/sh

# USAGE
# 	doas ./this-script
#
# DESCRIPTION
# 	Restarts the internet.
#
# 	There's another script around here that tells you
# 	all of the services you can enable.
#
# NOTES
# 	- Wait about 30 seconds for the wifi to reconnect.
#

service netif restart
